services:
    plenta.encryption:
        class: Plenta\ContaoEncryptionBundle\Classes\Encryption
        public: true
        arguments: ["%plenta_contao_encryption.encryption_key%"]

    brkwsky.encryption:
        alias: plenta.encryption
        public: true
        deprecated:
            message: 'The "%alias_id%" service alias is deprecated since plenta/contao-encryption 2.0.0. Please use "plenta.encryption" instead.'
            package: 'plenta/contao-encryption'
            version: '2.0.0'

    Plenta\ContaoEncryptionBundle\Classes\Encryption:
        alias: plenta.encryption
        public: true
