name: PHP Unit and Security Check

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: 'ubuntu-latest'
        strategy:
            matrix:
                php-versions: [ '7.4', '8.0', '8.1' ]
        name: PHP ${{ matrix.php-versions }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: ${{ matrix.php-versions }}
                extensions: mysqli, pdo_mysql, pcntl, bcmath, zip, soap, intl, gd, exif, xdebug
                ini-values: short_open_tag=off
                coverage: xdebug

            - name: Validate composer.json
              run: composer validate --no-check-lock

            - name: Install dependencies
              run: composer update --prefer-dist --no-progress --no-suggest

            - name: Security Checker
              uses: symfonycorp/security-checker-action@v2

            - name: PHPUnit
              run: vendor/bin/phpunit --configuration phpunit.xml.dist --testsuite unit
              env:
                SYMFONY_DEPRECATIONS_HELPER: disabled
